### ISSUE TITLE
Two-encoder multimode not working due to missing lib files. How do I reset cirtcuitpy?

### ISSUE THREAD

**Issue by thundernixon** [andyclymer/minikbd#5]
I've successfully set up a 6-key MiniKbd and I'm now working on the two-encoder version.

~~I am able to get this working with the `main.py` of the [Two-Encoder Keyboard](https://github.com/andyclymer/minikbd/tree/master/Software/TwoEncoder-Keyboard) configuration, but when I upload the `main.py` of the [Two Encoder Multimode](https://github.com/andyclymer/minikbd/tree/master/Software/TwoEncoder-Multimode) configuration, input is no longer registering.~~

~~I am trying to detect input with the [suggested terminal serial console](https://learn.adafruit.com/welcome-to-circuitpython/advanced-serial-console-on-mac-and-linux)~~

Actually, I'm now seeing that the input is triggered by `print` statements like `print("enc-1-up")` in the `main.py`. However, this has led into another error when I refresh the serial console:

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
ImportError: no module named 'adafruit_hid.consumer_control'
```

I see that there are lib files available such as [consumer_control_code](https://circuitpython.readthedocs.io/projects/hid/en/latest/_modules/adafruit_hid/consumer_control_code.html). I took the step (which I now see wasn't the best idea) of trying to reset my trinket m0, thinking that it must need the newer version. This has led me down a bit of a rabbithole.

I've tried to reset the trinket with the [Adafruit instructions here](https://learn.adafruit.com/adafruit-trinket-m0-circuitpython-arduino/circuitpython). However, I'm now unable to copy over the basic files. 

![image](https://user-images.githubusercontent.com/7355414/50523796-9d7c0180-0a97-11e9-9e8b-409d8a18e127.png)

![image](https://user-images.githubusercontent.com/7355414/50523861-ee8bf580-0a97-11e9-946f-636d4676d027.png)

I suspect that this may be due to my inability to delete the `.trashes` folder.

![image](https://user-images.githubusercontent.com/7355414/50523920-5a6e5e00-0a98-11e9-973d-45e82a83ee59.png)

I'll keep troubleshooting this and update here when I solve it. However, if anyone knows of any easy way to solve this, I'd appreciate some pointers!

(As a sidenote, it may be useful to include something in the files or in the readme of the multimode software about adding the necessary extra lib files).

**Comment by thundernixon** [comment]
I have found that it's simple to delete hidden files if I open CIRCUITPY in VS Code.

However, I am now trying to add in the correct `.mpy` files, but I get a "Not enough disk space" error:

![image](https://user-images.githubusercontent.com/7355414/50524751-1d589a80-0a9d-11e9-9272-98d7f7ef1da5.png)

**Comment by andyclymer** [comment]
First, you're on the right track.

The default configuration of a Trinket M0 doesn't have all of the Python packages installed because of (as you've noticed) the very limited amount of storage space on the device. The consumer_control library is one of those.

After updating to the latest version of Circuit Python, you'll want to also grab the latest release of the library (which it sounds like you've done) here:
https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases

Since there's such limited storage space on the device, try to remove any .mpy files that you don't need — for instance if you code no longer needs the mouse library or the neopixel library. And then empty your trash to completely remove the files. 

Adafruit also has some good advice here on keeping a drive space free with the Mac, try to see if any of this helps:
https://learn.adafruit.com/welcome-to-circuitpython/troubleshooting#running-out-of-file-space-on-non-express-boards-18-36

Give those a shot, and let me know if it helps!

**Comment by thundernixon** [comment]
Wow, that space really _is_ limited! The adafruit troubleshooting link you provided is very helpful, however. Thanks!

I was able to successfully delete everything via the terminal commands and start again, adding from files from the working other MiniKbd, plus some from the [`4.x` circuitpy release](https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases/download/20181229/adafruit-circuitpython-bundle-4.x-mpy-20181229.zip). However, I was getting an error: 

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
ValueError: Incompatible .mpy file. Please update all .mpy files. See http://adafru.it/mpy-update for more info.
```
I was able to solve this by really replacing _all_ the lib files with files from the `4.x` download, rather than just some of them. 

After bringing in the two-encoder py files, it's working like a charm to control volume in one mode, and brackets/zx in the other mode. 

Thanks for the help!

**Comment by andyclymer** [comment]
Yeah, the space is super limited. I think my next project will use the Adafruit ItsyBitsy or Feather which have a extra 265k of storage, which is massive in comparison :)

You're learning some good lessons with this project! And I'm learning what I need to update in the docs. If you upgraded to CircuitPython 4 on your Trinket, then as you found you do need to update all of the mpy files for version 4. I keep that `Adafruit_CircuitPython_Bundle` folder handy on my computer and only copy over the mpy files that I need at the moment.

Glad to see that it worked after you made that switch! I'll leave this issue open until I update the docs with a recommendation (but it will be pretty much exactly what you've done)

**Comment by thundernixon** [comment]
Ran into this again today, and https://learn.adafruit.com/welcome-to-circuitpython/troubleshooting#running-out-of-file-space-on-non-express-boards-18-36 really helped, particularly the steps shown on using the terminal to prevent metadata files and to copy over files without making new metadata files.
